// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package codec

import (
	"github.com/15mga/kiwi"
)

const (
	//心跳
	GateHeartbeatReq kiwi.TMethod = 0
	GateHeartbeatRes kiwi.TMethod = 1
	//错误推送
	GateErrPus             kiwi.TMethod = 2
	GateBanAddrReq         kiwi.TMethod = 500
	GateBanAddrRes         kiwi.TMethod = 501
	GateSendToIdReq        kiwi.TMethod = 502
	GateSendToIdRes        kiwi.TMethod = 503
	GateSendToAddrReq      kiwi.TMethod = 504
	GateSendToAddrRes      kiwi.TMethod = 505
	GateSendToMultiIdReq   kiwi.TMethod = 506
	GateSendToMultiIdRes   kiwi.TMethod = 507
	GateSendToMultiAddrReq kiwi.TMethod = 508
	GateSendToMultiAddrRes kiwi.TMethod = 509
	GateSendToAllReq       kiwi.TMethod = 510
	GateSendToAllRes       kiwi.TMethod = 511
	GateCloseIdReq         kiwi.TMethod = 512
	GateCloseIdRes         kiwi.TMethod = 513
	GateCloseAddrReq       kiwi.TMethod = 514
	GateCloseAddrRes       kiwi.TMethod = 515
	GateUpdateReq          kiwi.TMethod = 516
	GateUpdateRes          kiwi.TMethod = 517
	GateAddrUpdateReq      kiwi.TMethod = 518
	GateAddrUpdateRes      kiwi.TMethod = 519
	GateRemoveReq          kiwi.TMethod = 520
	GateRemoveRes          kiwi.TMethod = 521
	GateAddrRemoveReq      kiwi.TMethod = 522
	GateAddrRemoveRes      kiwi.TMethod = 523
	GateGetReq             kiwi.TMethod = 524
	GateGetRes             kiwi.TMethod = 525
	GateAddrGetReq         kiwi.TMethod = 526
	GateAddrGetRes         kiwi.TMethod = 527
)
