// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package codec

import (
	"github.com/15mga/kiwi"
)

const (
	//心跳
	GateHeartbeatReq kiwi.TMethod = 0
	GateHeartbeatRes kiwi.TMethod = 1
	//错误推送
	GateErrPus             kiwi.TMethod = 2
	GateSendToIdReq        kiwi.TMethod = 500
	GateSendToIdRes        kiwi.TMethod = 501
	GateSendToAddrReq      kiwi.TMethod = 502
	GateSendToAddrRes      kiwi.TMethod = 503
	GateSendToMultiIdReq   kiwi.TMethod = 504
	GateSendToMultiIdRes   kiwi.TMethod = 505
	GateSendToMultiAddrReq kiwi.TMethod = 506
	GateSendToMultiAddrRes kiwi.TMethod = 507
	GateSendToAllReq       kiwi.TMethod = 508
	GateSendToAllRes       kiwi.TMethod = 509
	GateCloseIdReq         kiwi.TMethod = 510
	GateCloseIdRes         kiwi.TMethod = 511
	GateCloseAddrReq       kiwi.TMethod = 512
	GateCloseAddrRes       kiwi.TMethod = 513
	GateUpdateReq          kiwi.TMethod = 514
	GateUpdateRes          kiwi.TMethod = 515
	GateRemoveReq          kiwi.TMethod = 516
	GateRemoveRes          kiwi.TMethod = 517
	GateGetReq             kiwi.TMethod = 518
	GateGetRes             kiwi.TMethod = 519
	GateUpdateRolesReq     kiwi.TMethod = 520
	GateUpdateRolesRes     kiwi.TMethod = 521
)
