// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package codec

import (
	"game/internal/common"
	"github.com/15mga/kiwi"
)

func BindReqToRes() {
	kiwi.Codec().BindReqToRes(common.Gate, GateHeartbeatReq, GateHeartbeatRes)
	kiwi.Codec().BindReqToRes(common.Gate, GateUploadFileReq, GateUploadFileRes)
	kiwi.Codec().BindReqToRes(common.Gate, GateUploadWithTokenReq, GateUploadWithTokenRes)
	kiwi.Codec().BindReqToRes(common.Gate, GateBanAddrReq, GateBanAddrRes)
	kiwi.Codec().BindReqToRes(common.Gate, GateSendToIdReq, GateSendToIdRes)
	kiwi.Codec().BindReqToRes(common.Gate, GateSendToAddrReq, GateSendToAddrRes)
	kiwi.Codec().BindReqToRes(common.Gate, GateSendToMultiIdReq, GateSendToMultiIdRes)
	kiwi.Codec().BindReqToRes(common.Gate, GateSendToMultiAddrReq, GateSendToMultiAddrRes)
	kiwi.Codec().BindReqToRes(common.Gate, GateSendToAllReq, GateSendToAllRes)
	kiwi.Codec().BindReqToRes(common.Gate, GateCloseIdReq, GateCloseIdRes)
	kiwi.Codec().BindReqToRes(common.Gate, GateCloseAddrReq, GateCloseAddrRes)
	kiwi.Codec().BindReqToRes(common.Gate, GateUpdateReq, GateUpdateRes)
	kiwi.Codec().BindReqToRes(common.Gate, GateAddrUpdateReq, GateAddrUpdateRes)
	kiwi.Codec().BindReqToRes(common.Gate, GateRemoveReq, GateRemoveRes)
	kiwi.Codec().BindReqToRes(common.Gate, GateAddrRemoveReq, GateAddrRemoveRes)
	kiwi.Codec().BindReqToRes(common.Gate, GateGetReq, GateGetRes)
	kiwi.Codec().BindReqToRes(common.Gate, GateAddrGetReq, GateAddrGetRes)
	kiwi.Codec().BindReqToRes(common.User, UserSignUpReq, UserSignUpRes)
	kiwi.Codec().BindReqToRes(common.User, UserSignInReq, UserSignInRes)
	kiwi.Codec().BindReqToRes(common.User, UserResetPasswordReq, UserResetPasswordRes)
	kiwi.Codec().BindReqToRes(common.User, UserSmsCodeReq, UserSmsCodeRes)
	kiwi.Codec().BindReqToRes(common.User, UserSignOutReq, UserSignOutRes)
	kiwi.Codec().BindReqToRes(common.User, UserDisconnectReq, UserDisconnectRes)
	kiwi.Codec().BindReqToRes(common.User, UserUpdateHeadReq, UserUpdateHeadRes)
}
