// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package codec

import (
	"github.com/15mga/kiwi"
)

const (
	//注册
	UserSignUpReq kiwi.TCode = 0
	//注册
	UserSignUpRes kiwi.TCode = 1
	//登录
	UserSignInReq kiwi.TCode = 2
	//登录
	UserSignInRes kiwi.TCode = 3
	//重置密码
	UserResetPasswordReq kiwi.TCode = 4
	//重置密码
	UserResetPasswordRes kiwi.TCode = 5
	//短信验证码
	UserSmsCodeReq kiwi.TCode = 6
	//短信验证码
	UserSmsCodeRes kiwi.TCode = 7
	//登出请求
	UserSignOutReq kiwi.TCode = 8
	//登出响应
	UserSignOutRes      kiwi.TCode = 9
	UserDisconnectReq   kiwi.TCode = 500
	UserDisconnectRes   kiwi.TCode = 501
	UserDisconnectedNtc kiwi.TCode = 502
	UserConnectedNtc    kiwi.TCode = 503
	//更新用户head cache
	UserUpdateHeadReq kiwi.TCode = 504
	UserUpdateHeadRes kiwi.TCode = 505
)
