// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package group

import (
	"game/proto/pb"
	"github.com/15mga/kiwi"
	"github.com/15mga/kiwi/util"
)

func (s *svc) OnGroupNew(pkt kiwi.IRcvRequest, req *pb.GroupNewReq, res *pb.GroupNewRes) {
	pkt.Err2(util.EcNotImplement, util.M{"req": req})
}
