// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package group

import (
	"game/internal/common"
	"github.com/15mga/kiwi"
	"github.com/15mga/kiwi/util"
)

var MsgRole = map[kiwi.TSvcMethod]int64{
	3000: util.GenMask(common.RPlayer),
}
