// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package group

import (
	"game/internal/common"
	"github.com/15mga/kiwi"
	"github.com/15mga/kiwi/core"
)

var (
	_svc *Svc
)

func New(ver string) kiwi.IService {
	_svc = &Svc{
		svc: svc{
			Service: core.NewService(common.Group, ver,
				common.Gate,
				common.User,
			),
		}}
	return _svc
}

// id: 3 name: group
type Svc struct {
	svc
}

// id: 3 name: group
type svc struct {
	core.Service
}

func (s *svc) Start() {
	registerReq()
}

func (s *svc) AfterStart() {
}
