// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package test

import (
	"game/internal/codec"
	"game/internal/common"
	"game/proto/pb"
	"github.com/15mga/kiwi"
	"github.com/15mga/kiwi/graph"
	"github.com/15mga/kiwi/mock"
	"github.com/15mga/kiwi/util"
	"strconv"
)

type Svc struct {
	svc
}

type svc struct {
	client *mock.Client
}

func InitClient(client *mock.Client) {
	s := &Svc{svc{client: client}}
	s.client.BindPointMsg("test", "TestPingPong", s.inTestPingPongReq)
	s.client.BindNetMsg(&pb.TestPingPongRes{}, s.onTestPingPongRes)
}

func (s *svc) Dispose() {
}

func (s *svc) Req(req util.IMsg) *util.Err {
	kiwi.Debug("request", util.M{string(req.ProtoReflect().Descriptor().Name()): req})
	svc, code := kiwi.Codec().MsgToSvcCode(req)
	bytes, err := common.PackUserReq(svc, code, req)
	if err != nil {
		return err
	}
	return s.client.Dialer().Agent().Send(bytes)
}

func (s *svc) inTestPingPongReq(msg graph.IMsg) *util.Err {
	req := s.client.GetRequest(common.Test, codec.TestPingPongReq)
	return s.Req(req)
}

func (s *svc) onTestPingPongRes(msg util.IMsg) (point string, data any) {
	sc := kiwi.MergeSvcCode(kiwi.Codec().MsgToSvcCode(msg))
	s.client.Graph().Data().Set(strconv.Itoa(int(sc)), msg)
	return "TestPingPong", nil
}
