mode: prod
log:
  std:
    enable: true
    log:
#      - debug
      - info
      - warn
      - error
      - fatal
    trace:
#      - debug
      - info
      - warn
      - error
      - fatal
  mgo:
    enable: false
    uri: mongodb://127.0.0.1:27017
    db: qiji_log
    log:
#      - debug
      - info
      - warn
      - error
      - fatal
    trace:
#      - debug
      - info
      - warn
      - error
      - fatal
    ttl: 604800 #7天
redis:
  addr: hw.15m.games:46379
  user: ""
  password: yo1peuBX6HJfoxuYe7Yx
  db: 0
mongo:
#  uri: mongodb://127.0.0.1:27017
  uri: mongodb://root:xa2jvO7dJT7d1iLA@hw.15m.games:47017/
  db: game
game:
  roundStartDur: 1500
  roundOverDur: 1500