// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package gate

import ()

const ()

const (
	GateRoleMethod = "method"
	GateRoleRoles  = "roles"
	GateRoleSvc    = "svc"

	GateUpdateRolesRoles = "roles"
	GateUpdateRolesSvc   = "svc"
)

func initColl() {
}
