// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package gate

import (
	"game/proto/pb"
	"github.com/15mga/kiwi/util"
	"github.com/15mga/kiwi/util/mgo"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/mongo"
)
