// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

using System;
using System.Collections.Generic;
using Google.Protobuf;

namespace Pb
{
	public static class Code
	{
		public static readonly Dictionary<Type, ushort> MsgTypeToCode = new()
		{
			{typeof(GateHeartbeatReq), 1000},
			{typeof(GateErrPus), 1002},
			{typeof(GateRepeatPus), 1003},
			{typeof(GateUploadFileReq), 1004},
			{typeof(GateUploadWithTokenReq), 1006},
			{typeof(GateUploadWithTokenPus), 1008},
			{typeof(UserSignUpReq), 2000},
			{typeof(UserSignInReq), 2002},
			{typeof(UserResetPasswordReq), 2004},
			{typeof(UserSmsCodeReq), 2006},
			{typeof(UserSignOutReq), 2008},
			{typeof(GroupNewReq), 3000},
		};

		public static readonly Dictionary<ushort, Func<byte[], IMessage>> CodeToMsg = new()
		{
			{1001, GateHeartbeatRes.Parser.ParseFrom},
			{1002, GateErrPus.Parser.ParseFrom},
			{1003, GateRepeatPus.Parser.ParseFrom},
			{1005, GateUploadFileRes.Parser.ParseFrom},
			{1007, GateUploadWithTokenRes.Parser.ParseFrom},
			{1008, GateUploadWithTokenPus.Parser.ParseFrom},
			{2001, UserSignUpRes.Parser.ParseFrom},
			{2003, UserSignInRes.Parser.ParseFrom},
			{2005, UserResetPasswordRes.Parser.ParseFrom},
			{2007, UserSmsCodeRes.Parser.ParseFrom},
			{2009, UserSignOutRes.Parser.ParseFrom},
		};

		public static readonly Dictionary<ushort, ushort> ReqToRes = new()
		{
			{1000, 1001},
			{1004, 1005},
			{1006, 1007},
			{2000, 2001},
			{2002, 2003},
			{2004, 2005},
			{2006, 2007},
			{2008, 2009},
		};
	}
}