// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

using System;
using System.Collections.Generic;
using Google.Protobuf;

namespace Pb
{
	public static class Code
	{
		public static readonly Dictionary<Type, ushort> MsgTypeToCode = new()
		{
			{typeof(GateHeartbeatReq), 1000},
			{typeof(GateErrPus), 1002},
			{typeof(UserSignUpWithMobileReq), 2000},
			{typeof(UserSignInWithMobileReq), 2002},
			{typeof(UserResetPasswordWithMobileReq), 2004},
			{typeof(UserCodeWithMobileReq), 2006},
			{typeof(UserSignUpWithEmailReq), 2008},
			{typeof(UserSignInWithEmailReq), 2010},
			{typeof(UserResetPasswordWithEmailReq), 2012},
			{typeof(UserCodeWithEmailReq), 2014},
			{typeof(UserSignInWithWechatReq), 2016},
			{typeof(UserNewReq), 2018},
			{typeof(UserSignInReq), 2020},
			{typeof(UserSignOutReq), 2022},
			{typeof(UserReconnectReq), 2024},
			{typeof(UserRepeatSignInPus), 2026},
			{typeof(GroupNewReq), 3000},
		};

		public static readonly Dictionary<ushort, Func<byte[], IMessage>> CodeToMsg = new()
		{
			{1001, GateHeartbeatRes.Parser.ParseFrom},
			{1002, GateErrPus.Parser.ParseFrom},
			{2001, UserSignUpWithMobileRes.Parser.ParseFrom},
			{2003, UserSignInWithMobileRes.Parser.ParseFrom},
			{2005, UserResetPasswordWithMobileRes.Parser.ParseFrom},
			{2007, UserCodeWithMobileRes.Parser.ParseFrom},
			{2009, UserSignUpWithEmailRes.Parser.ParseFrom},
			{2011, UserSignInWithEmailRes.Parser.ParseFrom},
			{2013, UserResetPasswordWithEmailRes.Parser.ParseFrom},
			{2015, UserCodeWithEmailRes.Parser.ParseFrom},
			{2017, UserSignInWithWechatRes.Parser.ParseFrom},
			{2019, UserNewRes.Parser.ParseFrom},
			{2021, UserSignInRes.Parser.ParseFrom},
			{2023, UserSignOutRes.Parser.ParseFrom},
			{2025, UserReconnectRes.Parser.ParseFrom},
			{2026, UserRepeatSignInPus.Parser.ParseFrom},
			{3001, GroupNewRes.Parser.ParseFrom},
		};

		public static readonly Dictionary<ushort, ushort> ReqToRes = new()
		{
			{1000, 1001},
			{2000, 2001},
			{2002, 2003},
			{2004, 2005},
			{2006, 2007},
			{2008, 2009},
			{2010, 2011},
			{2012, 2013},
			{2014, 2015},
			{2016, 2017},
			{2018, 2019},
			{2020, 2021},
			{2022, 2023},
			{2024, 2025},
			{3000, 3001},
		};
	}
}