// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package user

import (
	"github.com/15mga/kiwi/util/mgo"
	"go.mongodb.org/mongo-driver/mongo"
)

const (
	SchemaUser = "user"
)

const (
	TestAge  = "age"
	TestName = "name"

	Id              = "_id"
	Addr            = "addr"              //地址
	Avatar          = "avatar"            //头像地址
	Ban             = "ban"               //禁用
	Head            = "head"              //会话
	IdCard          = "id_card"           //身份证
	LastOfflineTime = "last_offline_time" //最后下线时间
	LastOs          = "last_os"           //最后登录使用的系统
	LastSignInIp    = "last_sign_in_ip"   //最后登录地址
	LastSignInTime  = "last_sign_in_time" //最后登录时间
	Mobile          = "mobile"            //手机号
	Nick            = "nick"              //昵称
	OnlineDur       = "online_dur"        //在线时长
	Password        = "password"
	RealName        = "real_name"    //实名
	RoleMask        = "role_mask"    //角色组：1:访客，2：玩家，
	SignUpTime      = "sign_up_time" //注册时间
	State           = "state"        //状态
	Test            = "test"         //测试账号
	TestBool        = "test_bool"
	TestData        = "test_data"
	TestData2       = "test_data2"
	TestI32         = "test_i32"
	TestString      = "test_string"
	Token           = "token"           //token
	WechatUnionId   = "wechat_union_id" //微信联合 id
)

func initColl() {
	mgo.InitColl(SchemaUser, UserIdx)
}

func UserIdx() []mongo.IndexModel {
	return []mongo.IndexModel{}
}
