// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package user

import (
	"github.com/15mga/kiwi/util/mgo"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
)

const (
	SchemaMobileAccount = "mobile_account"
	SchemaEmailAccount  = "email_account"
	SchemaWechatAccount = "wechat_account"
	SchemaUser          = "user"
)

const (
	EmailAccountId       = "_id" // email
	EmailAccountPassword = "password"
	EmailAccountUserId   = "user_id"

	MobileAccountId       = "_id" // mobile
	MobileAccountPassword = "password"
	MobileAccountUserId   = "user_id"

	Id              = "_id"
	Avatar          = "avatar"            //头像地址
	Ban             = "ban"               //禁用
	CreateTime      = "create_time"       //创建时间
	Head            = "head"              //会话
	IdCard          = "id_card"           //身份证
	LastOfflineTime = "last_offline_time" //最后下线时间
	LastOs          = "last_os"           //最后登录使用的系统
	LastSignInAddr  = "last_sign_in_addr" //最后登录地址
	LastSignInTime  = "last_sign_in_time" //最后登录时间
	Nick            = "nick"              //昵称
	OnlineDur       = "online_dur"        //在线时长
	RealName        = "real_name"         //实名
	RoleMask        = "role_mask"         //角色组遮罩
	State           = "state"             //状态
	Token           = "token"             //token

	WechatAccountId     = "_id" // wechatUnionId 微信联合 id
	WechatAccountUserId = "user_id"
)

func initColl() {
	mgo.InitColl(SchemaMobileAccount, MobileAccountIdx)
	mgo.InitColl(SchemaEmailAccount, EmailAccountIdx)
	mgo.InitColl(SchemaWechatAccount, WechatAccountIdx)
	mgo.InitColl(SchemaUser, UserIdx)
}

func MobileAccountIdx() []mongo.IndexModel {
	return []mongo.IndexModel{
		{
			Keys: bson.D{
				{"user_id", 1},
			},
		},
	}
}

func EmailAccountIdx() []mongo.IndexModel {
	return []mongo.IndexModel{
		{
			Keys: bson.D{
				{"user_id", 1},
			},
		},
	}
}

func WechatAccountIdx() []mongo.IndexModel {
	return []mongo.IndexModel{
		{
			Keys: bson.D{
				{"user_id", 1},
			},
		},
	}
}

func UserIdx() []mongo.IndexModel {
	return []mongo.IndexModel{
		{
			Keys: bson.D{
				{"nick", 1},
			},
			Options: options.Index().SetUnique(true),
		},
		{
			Keys: bson.D{
				{"token", 1},
			},
			Options: options.Index().SetUnique(true),
		},
		{
			Keys: bson.D{
				{"ban", 1},
			},
		},
		{
			Keys: bson.D{
				{"sign_up_time", 1},
			},
		},
		{
			Keys: bson.D{
				{"last_sign_in_time", 1},
			},
		},
		{
			Keys: bson.D{
				{"last_sign_in_ip", 1},
			},
		},
		{
			Keys: bson.D{
				{"state", 1},
			},
		},
	}
}
