// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package user

import (
	"game/proto/pb"
	"github.com/15mga/kiwi/ds"
	"github.com/15mga/kiwi/util/mgo"
)

var (
	_SchemaFac = map[string]func() mgo.IModel{
		SchemaUser: NewUser,
	}
)

var (
	_UserSet = ds.NewKSet[string, *User](1024, func(model *User) string {
		return model.Id
	})
	_mobileSet = ds.NewKSet[string, *User](1024, func(model *User) string {
	})
	_nickSet = ds.NewKSet[string, *User](1024, func(model *User) string {
	})
	_id_cardSet = ds.NewKSet[string, *User](1024, func(model *User) string {
	})
	_sign_up_timeSet = ds.NewKSet[string, *User](1024, func(model *User) string {
	})
	_last_sign_in_timeSet = ds.NewKSet[string, *User](1024, func(model *User) string {
	})
	_last_sign_in_addrSet = ds.NewKSet[string, *User](1024, func(model *User) string {
	})
	_stateSet = ds.NewKSet[string, *User](1024, func(model *User) string {
	})
	_wechat_union_idSet = ds.NewKSet[string, *User](1024, func(model *User) string {
	})
	_tokenSet = ds.NewKSet[string, *User](1024, func(model *User) string {
	})
	_wechat_codeSet = ds.NewKSet[string, *User](1024, func(model *User) string {
	})
)

func addUser(m *User) {
	_UserSet.Add(m)
}

func GetUser(id string) *User {
	m, ok := _UserSet.Get(id)
	if ok {
		return m
	}
	m = _SchemaFac[SchemaUser]().(*User)
	m.Load(id)
	addUser(m)
	return m
}

func LoadUser(filter any) *User {
	m := _SchemaFac[SchemaUser]().(*User)
	m.LoadWithFilter(filter)
	_UserSet.Add(m)
	return m
}

func NewUser() mgo.IModel {
	m := &User{
		User: &pb.User{},
	}
	m.Model = mgo.NewModel(SchemaUser, 23, m.GetVal)
	return m
}

type User struct {
	*pb.User
	*mgo.Model
}

func (this *User) SetPassword(val string) {
	this.Password = val
	this.SetDirty(Password)
}

func (this *User) SetRoleMask(val int64) {
	this.RoleMask = val
	this.SetDirty(RoleMask)
}

func (this *User) SetBan(val bool) {
	this.Ban = val
	this.SetDirty(Ban)
}

func (this *User) SetNick(val string) {
	this.Nick = val
	this.SetDirty(Nick)
}

func (this *User) SetAddr(val string) {
	this.Addr = val
	this.SetDirty(Addr)
}

func (this *User) SetIdCard(val string) {
	this.IdCard = val
	this.SetDirty(IdCard)
}

func (this *User) SetRealName(val string) {
	this.RealName = val
	this.SetDirty(RealName)
}

func (this *User) SetMobile(val string) {
	this.Mobile = val
	this.SetDirty(Mobile)
}

func (this *User) SetSignUpTime(val int64) {
	this.SignUpTime = val
	this.SetDirty(SignUpTime)
}

func (this *User) SetLastSignInTime(val int64) {
	this.LastSignInTime = val
	this.SetDirty(LastSignInTime)
}

func (this *User) SetLastSignInAddr(val string) {
	this.LastSignInAddr = val
	this.SetDirty(LastSignInAddr)
}

func (this *User) SetLastOs(val string) {
	this.LastOs = val
	this.SetDirty(LastOs)
}

func (this *User) SetStatus(val pb.OnlineState) {
	this.Status = val
	this.SetDirty(Status)
}

func (this *User) SetAvatar(val string) {
	this.Avatar = val
	this.SetDirty(Avatar)
}

func (this *User) SetWechatUnionId(val string) {
	this.WechatUnionId = val
	this.SetDirty(WechatUnionId)
}

func (this *User) SetWechatCode(val string) {
	this.WechatCode = val
	this.SetDirty(WechatCode)
}

func (this *User) SetToken(val string) {
	this.Token = val
	this.SetDirty(Token)
}

func (this *User) SetHead(val []byte) {
	this.Head = val
	this.SetDirty(Head)
}

func (this *User) SetLastOfflineTime(val int64) {
	this.LastOfflineTime = val
	this.SetDirty(LastOfflineTime)
}

func (this *User) SetOnlineDur(val int64) {
	this.OnlineDur = val
	this.SetDirty(OnlineDur)
}

func (this *User) SetTest(val bool) {
	this.Test = val
	this.SetDirty(Test)
}

func (this *User) SetCharacterIds(val []string) {
	this.CharacterIds = val
	this.SetDirty(CharacterIds)
}

func (this *User) PushCharacterIds(items ...string) {
	this.CharacterIds = append(this.CharacterIds, items...)
	this.SetDirty(CharacterIds)
}

func (this *User) AddToSetCharacterIds(items ...string) {
	for _, item := range items {
		for _, v := range this.CharacterIds {
			if v == item {
				return
			}
		}
		this.CharacterIds = append(this.CharacterIds, item)
	}
	this.SetDirty(CharacterIds)
}

func (this *User) PullCharacterIds(items ...string) {
	if this.CharacterIds == nil || len(this.CharacterIds) == 0 {
		return
	}
	dirty := false
	for _, item := range items {
		for i, v := range this.CharacterIds {
			if v == item {
				this.CharacterIds = append(this.CharacterIds[:i], this.CharacterIds[i+1:]...)
				dirty = true
				break
			}
		}
	}
	if dirty {
		this.SetDirty(CharacterIds)
	}
}

func (this *User) GetVal(key string) any {
	switch key {
	case Password:
		return this.Password
	case RoleMask:
		return this.RoleMask
	case Ban:
		return this.Ban
	case Nick:
		return this.Nick
	case Addr:
		return this.Addr
	case IdCard:
		return this.IdCard
	case RealName:
		return this.RealName
	case Mobile:
		return this.Mobile
	case SignUpTime:
		return this.SignUpTime
	case LastSignInTime:
		return this.LastSignInTime
	case LastSignInAddr:
		return this.LastSignInAddr
	case LastOs:
		return this.LastOs
	case Status:
		return this.Status
	case Avatar:
		return this.Avatar
	case WechatUnionId:
		return this.WechatUnionId
	case WechatCode:
		return this.WechatCode
	case Token:
		return this.Token
	case Head:
		return this.Head
	case LastOfflineTime:
		return this.LastOfflineTime
	case OnlineDur:
		return this.OnlineDur
	case Test:
		return this.Test
	case CharacterIds:
		return this.CharacterIds
	default:
		return nil
	}
}
