// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package user

import (
	"game/internal/common"
	"github.com/15mga/kiwi"
	"github.com/15mga/kiwi/util"
)

var MsgRole = map[kiwi.TSvcMethod]int64{
	2000: util.GenMask(common.RGuest),
	2002: util.GenMask(common.RGuest),
	2004: util.GenMask(common.RGuest),
	2006: util.GenMask(common.RGuest),
	2008: util.GenMask(common.RGuest),
	2010: util.GenMask(common.RGuest),
	2012: util.GenMask(common.RGuest),
	2014: util.GenMask(common.RGuest),
	2016: util.GenMask(common.RGuest),
	2018: util.GenMask(common.RPlayer),
	2020: util.GenMask(common.RPlayer),
	2022: util.GenMask(common.RPlayer),
	2024: util.GenMask(common.RPlayer),
}
