// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: client/gate_c.proto

package pb

import (
	_ "github.com/15mga/kiwi_tool"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 心跳
type GateHeartbeatReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqTs int64 `protobuf:"varint,1,opt,name=reqTs,proto3" json:"reqTs" bson:"req_ts"`
}

func (x *GateHeartbeatReq) Reset() {
	*x = GateHeartbeatReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_gate_c_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateHeartbeatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateHeartbeatReq) ProtoMessage() {}

func (x *GateHeartbeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_gate_c_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateHeartbeatReq.ProtoReflect.Descriptor instead.
func (*GateHeartbeatReq) Descriptor() ([]byte, []int) {
	return file_client_gate_c_proto_rawDescGZIP(), []int{0}
}

func (x *GateHeartbeatReq) GetReqTs() int64 {
	if x != nil {
		return x.ReqTs
	}
	return 0
}

type GateHeartbeatRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqTs int64 `protobuf:"varint,1,opt,name=reqTs,proto3" json:"reqTs" bson:"req_ts"`
	ResTs int64 `protobuf:"varint,2,opt,name=resTs,proto3" json:"resTs" bson:"res_ts"`
}

func (x *GateHeartbeatRes) Reset() {
	*x = GateHeartbeatRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_gate_c_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateHeartbeatRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateHeartbeatRes) ProtoMessage() {}

func (x *GateHeartbeatRes) ProtoReflect() protoreflect.Message {
	mi := &file_client_gate_c_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateHeartbeatRes.ProtoReflect.Descriptor instead.
func (*GateHeartbeatRes) Descriptor() ([]byte, []int) {
	return file_client_gate_c_proto_rawDescGZIP(), []int{1}
}

func (x *GateHeartbeatRes) GetReqTs() int64 {
	if x != nil {
		return x.ReqTs
	}
	return 0
}

func (x *GateHeartbeatRes) GetResTs() int64 {
	if x != nil {
		return x.ResTs
	}
	return 0
}

// 错误推送
type GateErrPus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgCode int32 `protobuf:"varint,1,opt,name=msgCode,proto3" json:"msgCode" bson:"msg_code"` //响应消息协议号
	ErrCode int32 `protobuf:"varint,2,opt,name=errCode,proto3" json:"errCode" bson:"err_code"` //配置表
}

func (x *GateErrPus) Reset() {
	*x = GateErrPus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_gate_c_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateErrPus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateErrPus) ProtoMessage() {}

func (x *GateErrPus) ProtoReflect() protoreflect.Message {
	mi := &file_client_gate_c_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateErrPus.ProtoReflect.Descriptor instead.
func (*GateErrPus) Descriptor() ([]byte, []int) {
	return file_client_gate_c_proto_rawDescGZIP(), []int{2}
}

func (x *GateErrPus) GetMsgCode() int32 {
	if x != nil {
		return x.MsgCode
	}
	return 0
}

func (x *GateErrPus) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

// 重复链接推送
type GateRepeatPus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GateRepeatPus) Reset() {
	*x = GateRepeatPus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_gate_c_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateRepeatPus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateRepeatPus) ProtoMessage() {}

func (x *GateRepeatPus) ProtoReflect() protoreflect.Message {
	mi := &file_client_gate_c_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateRepeatPus.ProtoReflect.Descriptor instead.
func (*GateRepeatPus) Descriptor() ([]byte, []int) {
	return file_client_gate_c_proto_rawDescGZIP(), []int{3}
}

// 上传图片
type GateUploadFileReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    string `protobuf:"bytes,1,opt,name=type,proto3" json:"type" bson:"type"`           //poster:海报 公告:announcement 亲友圈:group 头像:avatar
	FileExt string `protobuf:"bytes,2,opt,name=fileExt,proto3" json:"fileExt" bson:"file_ext"` //文件后缀 .jpg, .png
	Data    string `protobuf:"bytes,3,opt,name=data,proto3" json:"data" bson:"data"`           //文件数据
}

func (x *GateUploadFileReq) Reset() {
	*x = GateUploadFileReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_gate_c_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateUploadFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateUploadFileReq) ProtoMessage() {}

func (x *GateUploadFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_gate_c_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateUploadFileReq.ProtoReflect.Descriptor instead.
func (*GateUploadFileReq) Descriptor() ([]byte, []int) {
	return file_client_gate_c_proto_rawDescGZIP(), []int{4}
}

func (x *GateUploadFileReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GateUploadFileReq) GetFileExt() string {
	if x != nil {
		return x.FileExt
	}
	return ""
}

func (x *GateUploadFileReq) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type GateUploadFileRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url" bson:"url"` //文件服务器地址
}

func (x *GateUploadFileRes) Reset() {
	*x = GateUploadFileRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_gate_c_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateUploadFileRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateUploadFileRes) ProtoMessage() {}

func (x *GateUploadFileRes) ProtoReflect() protoreflect.Message {
	mi := &file_client_gate_c_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateUploadFileRes.ProtoReflect.Descriptor instead.
func (*GateUploadFileRes) Descriptor() ([]byte, []int) {
	return file_client_gate_c_proto_rawDescGZIP(), []int{5}
}

func (x *GateUploadFileRes) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GateUploadWithTokenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    string `protobuf:"bytes,1,opt,name=type,proto3" json:"type" bson:"type"`           //poster:海报 公告:announcement 亲友圈:group 头像:avatar
	FileExt string `protobuf:"bytes,2,opt,name=fileExt,proto3" json:"fileExt" bson:"file_ext"` //文件后缀 .jpg, .png
	Data    string `protobuf:"bytes,3,opt,name=data,proto3" json:"data" bson:"data"`           //文件数据
	Token   string `protobuf:"bytes,4,opt,name=token,proto3" json:"token" bson:"token"`        //
}

func (x *GateUploadWithTokenReq) Reset() {
	*x = GateUploadWithTokenReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_gate_c_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateUploadWithTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateUploadWithTokenReq) ProtoMessage() {}

func (x *GateUploadWithTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_gate_c_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateUploadWithTokenReq.ProtoReflect.Descriptor instead.
func (*GateUploadWithTokenReq) Descriptor() ([]byte, []int) {
	return file_client_gate_c_proto_rawDescGZIP(), []int{6}
}

func (x *GateUploadWithTokenReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GateUploadWithTokenReq) GetFileExt() string {
	if x != nil {
		return x.FileExt
	}
	return ""
}

func (x *GateUploadWithTokenReq) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *GateUploadWithTokenReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GateUploadWithTokenRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url" bson:"url"` //文件服务器地址
}

func (x *GateUploadWithTokenRes) Reset() {
	*x = GateUploadWithTokenRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_gate_c_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateUploadWithTokenRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateUploadWithTokenRes) ProtoMessage() {}

func (x *GateUploadWithTokenRes) ProtoReflect() protoreflect.Message {
	mi := &file_client_gate_c_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateUploadWithTokenRes.ProtoReflect.Descriptor instead.
func (*GateUploadWithTokenRes) Descriptor() ([]byte, []int) {
	return file_client_gate_c_proto_rawDescGZIP(), []int{7}
}

func (x *GateUploadWithTokenRes) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GateUploadWithTokenPus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url" bson:"url"` //文件服务器地址
}

func (x *GateUploadWithTokenPus) Reset() {
	*x = GateUploadWithTokenPus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_gate_c_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateUploadWithTokenPus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateUploadWithTokenPus) ProtoMessage() {}

func (x *GateUploadWithTokenPus) ProtoReflect() protoreflect.Message {
	mi := &file_client_gate_c_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateUploadWithTokenPus.ProtoReflect.Descriptor instead.
func (*GateUploadWithTokenPus) Descriptor() ([]byte, []int) {
	return file_client_gate_c_proto_rawDescGZIP(), []int{8}
}

func (x *GateUploadWithTokenPus) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_client_gate_c_proto protoreflect.FileDescriptor

var file_client_gate_c_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x5f, 0x63, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x31, 0x35, 0x6d, 0x67, 0x61, 0x2f, 0x6b, 0x69, 0x77, 0x69,
	0x5f, 0x74, 0x6f, 0x6f, 0x6c, 0x2f, 0x6b, 0x69, 0x77, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x48, 0x0a, 0x10, 0x47, 0x61, 0x74, 0x65, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x71, 0x54, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x72, 0x65, 0x71, 0x54, 0x73, 0x3a, 0x1e, 0xe0, 0xe3, 0x49, 0x00,
	0xea, 0xe3, 0x49, 0x05, 0x67, 0x75, 0x65, 0x73, 0x74, 0xea, 0xe3, 0x49, 0x06, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0xea, 0xe3, 0x49, 0x03, 0x6f, 0x70, 0x73, 0x22, 0x44, 0x0a, 0x10, 0x47, 0x61,
	0x74, 0x65, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x72, 0x65, 0x71, 0x54, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x72,
	0x65, 0x71, 0x54, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x73, 0x54, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x72, 0x65, 0x73, 0x54, 0x73, 0x3a, 0x04, 0xe0, 0xe3, 0x49, 0x01,
	0x22, 0x46, 0x0a, 0x0a, 0x47, 0x61, 0x74, 0x65, 0x45, 0x72, 0x72, 0x50, 0x75, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x73, 0x67, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x6d, 0x73, 0x67, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x3a, 0x04, 0xe0, 0xe3, 0x49, 0x02, 0x22, 0x15, 0x0a, 0x0d, 0x47, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x50, 0x75, 0x73, 0x3a, 0x04, 0xe0, 0xe3, 0x49, 0x03, 0x22,
	0x6c, 0x0a, 0x11, 0x47, 0x61, 0x74, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65,
	0x45, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x45,
	0x78, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x3a, 0x15, 0xe0, 0xe3, 0x49, 0x04, 0xea, 0xe3, 0x49, 0x06,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0xea, 0xe3, 0x49, 0x03, 0x6f, 0x70, 0x73, 0x22, 0x2b, 0x0a,
	0x11, 0x47, 0x61, 0x74, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x72, 0x6c, 0x3a, 0x04, 0xe0, 0xe3, 0x49, 0x05, 0x22, 0x7f, 0x0a, 0x16, 0x47, 0x61,
	0x74, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x57, 0x69, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65,
	0x45, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x45,
	0x78, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x3a, 0x0d, 0xe0, 0xe3,
	0x49, 0x06, 0xea, 0xe3, 0x49, 0x05, 0x67, 0x75, 0x65, 0x73, 0x74, 0x22, 0x30, 0x0a, 0x16, 0x47,
	0x61, 0x74, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x57, 0x69, 0x74, 0x68, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x3a, 0x04, 0xe0, 0xe3, 0x49, 0x07, 0x22, 0x30, 0x0a,
	0x16, 0x47, 0x61, 0x74, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x57, 0x69, 0x74, 0x68, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x50, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x3a, 0x04, 0xe0, 0xe3, 0x49, 0x08, 0x42,
	0x14, 0xca, 0xdd, 0x49, 0x06, 0x12, 0x04, 0x67, 0x61, 0x74, 0x65, 0x5a, 0x03, 0x2f, 0x70, 0x62,
	0xaa, 0x02, 0x02, 0x50, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_client_gate_c_proto_rawDescOnce sync.Once
	file_client_gate_c_proto_rawDescData = file_client_gate_c_proto_rawDesc
)

func file_client_gate_c_proto_rawDescGZIP() []byte {
	file_client_gate_c_proto_rawDescOnce.Do(func() {
		file_client_gate_c_proto_rawDescData = protoimpl.X.CompressGZIP(file_client_gate_c_proto_rawDescData)
	})
	return file_client_gate_c_proto_rawDescData
}

var file_client_gate_c_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_client_gate_c_proto_goTypes = []interface{}{
	(*GateHeartbeatReq)(nil),       // 0: pb.GateHeartbeatReq
	(*GateHeartbeatRes)(nil),       // 1: pb.GateHeartbeatRes
	(*GateErrPus)(nil),             // 2: pb.GateErrPus
	(*GateRepeatPus)(nil),          // 3: pb.GateRepeatPus
	(*GateUploadFileReq)(nil),      // 4: pb.GateUploadFileReq
	(*GateUploadFileRes)(nil),      // 5: pb.GateUploadFileRes
	(*GateUploadWithTokenReq)(nil), // 6: pb.GateUploadWithTokenReq
	(*GateUploadWithTokenRes)(nil), // 7: pb.GateUploadWithTokenRes
	(*GateUploadWithTokenPus)(nil), // 8: pb.GateUploadWithTokenPus
}
var file_client_gate_c_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_client_gate_c_proto_init() }
func file_client_gate_c_proto_init() {
	if File_client_gate_c_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_client_gate_c_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateHeartbeatReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_gate_c_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateHeartbeatRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_gate_c_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateErrPus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_gate_c_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateRepeatPus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_gate_c_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateUploadFileReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_gate_c_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateUploadFileRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_gate_c_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateUploadWithTokenReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_gate_c_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateUploadWithTokenRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_gate_c_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateUploadWithTokenPus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_client_gate_c_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_gate_c_proto_goTypes,
		DependencyIndexes: file_client_gate_c_proto_depIdxs,
		MessageInfos:      file_client_gate_c_proto_msgTypes,
	}.Build()
	File_client_gate_c_proto = out.File
	file_client_gate_c_proto_rawDesc = nil
	file_client_gate_c_proto_goTypes = nil
	file_client_gate_c_proto_depIdxs = nil
}
