// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.20.1
// source: service/gate_s.proto

package pb

import (
	_ "github.com/15mga/kiwi_tool"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GateBanAddrReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty" bson:"addr"`
}

func (x *GateBanAddrReq) Reset() {
	*x = GateBanAddrReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gate_s_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateBanAddrReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateBanAddrReq) ProtoMessage() {}

func (x *GateBanAddrReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_gate_s_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateBanAddrReq.ProtoReflect.Descriptor instead.
func (*GateBanAddrReq) Descriptor() ([]byte, []int) {
	return file_service_gate_s_proto_rawDescGZIP(), []int{0}
}

func (x *GateBanAddrReq) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type GateBanAddrRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GateBanAddrRes) Reset() {
	*x = GateBanAddrRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gate_s_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateBanAddrRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateBanAddrRes) ProtoMessage() {}

func (x *GateBanAddrRes) ProtoReflect() protoreflect.Message {
	mi := &file_service_gate_s_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateBanAddrRes.ProtoReflect.Descriptor instead.
func (*GateBanAddrRes) Descriptor() ([]byte, []int) {
	return file_service_gate_s_proto_rawDescGZIP(), []int{1}
}

type GateSendToIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id"`
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty" bson:"payload"`
}

func (x *GateSendToIdReq) Reset() {
	*x = GateSendToIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gate_s_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateSendToIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateSendToIdReq) ProtoMessage() {}

func (x *GateSendToIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_gate_s_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateSendToIdReq.ProtoReflect.Descriptor instead.
func (*GateSendToIdReq) Descriptor() ([]byte, []int) {
	return file_service_gate_s_proto_rawDescGZIP(), []int{2}
}

func (x *GateSendToIdReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GateSendToIdReq) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type GateSendToIdRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GateSendToIdRes) Reset() {
	*x = GateSendToIdRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gate_s_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateSendToIdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateSendToIdRes) ProtoMessage() {}

func (x *GateSendToIdRes) ProtoReflect() protoreflect.Message {
	mi := &file_service_gate_s_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateSendToIdRes.ProtoReflect.Descriptor instead.
func (*GateSendToIdRes) Descriptor() ([]byte, []int) {
	return file_service_gate_s_proto_rawDescGZIP(), []int{3}
}

type GateSendToAddrReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr    string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty" bson:"addr"`
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty" bson:"payload"`
}

func (x *GateSendToAddrReq) Reset() {
	*x = GateSendToAddrReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gate_s_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateSendToAddrReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateSendToAddrReq) ProtoMessage() {}

func (x *GateSendToAddrReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_gate_s_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateSendToAddrReq.ProtoReflect.Descriptor instead.
func (*GateSendToAddrReq) Descriptor() ([]byte, []int) {
	return file_service_gate_s_proto_rawDescGZIP(), []int{4}
}

func (x *GateSendToAddrReq) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *GateSendToAddrReq) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type GateSendToAddrRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GateSendToAddrRes) Reset() {
	*x = GateSendToAddrRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gate_s_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateSendToAddrRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateSendToAddrRes) ProtoMessage() {}

func (x *GateSendToAddrRes) ProtoReflect() protoreflect.Message {
	mi := &file_service_gate_s_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateSendToAddrRes.ProtoReflect.Descriptor instead.
func (*GateSendToAddrRes) Descriptor() ([]byte, []int) {
	return file_service_gate_s_proto_rawDescGZIP(), []int{5}
}

type GateSendToMultiIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty" bson:"payload"`
}

func (x *GateSendToMultiIdReq) Reset() {
	*x = GateSendToMultiIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gate_s_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateSendToMultiIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateSendToMultiIdReq) ProtoMessage() {}

func (x *GateSendToMultiIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_gate_s_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateSendToMultiIdReq.ProtoReflect.Descriptor instead.
func (*GateSendToMultiIdReq) Descriptor() ([]byte, []int) {
	return file_service_gate_s_proto_rawDescGZIP(), []int{6}
}

func (x *GateSendToMultiIdReq) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type GateSendToMultiIdRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result map[string]bool `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3" bson:"result"`
}

func (x *GateSendToMultiIdRes) Reset() {
	*x = GateSendToMultiIdRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gate_s_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateSendToMultiIdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateSendToMultiIdRes) ProtoMessage() {}

func (x *GateSendToMultiIdRes) ProtoReflect() protoreflect.Message {
	mi := &file_service_gate_s_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateSendToMultiIdRes.ProtoReflect.Descriptor instead.
func (*GateSendToMultiIdRes) Descriptor() ([]byte, []int) {
	return file_service_gate_s_proto_rawDescGZIP(), []int{7}
}

func (x *GateSendToMultiIdRes) GetResult() map[string]bool {
	if x != nil {
		return x.Result
	}
	return nil
}

type GateSendToMultiAddrReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty" bson:"payload"`
}

func (x *GateSendToMultiAddrReq) Reset() {
	*x = GateSendToMultiAddrReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gate_s_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateSendToMultiAddrReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateSendToMultiAddrReq) ProtoMessage() {}

func (x *GateSendToMultiAddrReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_gate_s_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateSendToMultiAddrReq.ProtoReflect.Descriptor instead.
func (*GateSendToMultiAddrReq) Descriptor() ([]byte, []int) {
	return file_service_gate_s_proto_rawDescGZIP(), []int{8}
}

func (x *GateSendToMultiAddrReq) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type GateSendToMultiAddrRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result map[string]bool `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3" bson:"result"`
}

func (x *GateSendToMultiAddrRes) Reset() {
	*x = GateSendToMultiAddrRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gate_s_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateSendToMultiAddrRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateSendToMultiAddrRes) ProtoMessage() {}

func (x *GateSendToMultiAddrRes) ProtoReflect() protoreflect.Message {
	mi := &file_service_gate_s_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateSendToMultiAddrRes.ProtoReflect.Descriptor instead.
func (*GateSendToMultiAddrRes) Descriptor() ([]byte, []int) {
	return file_service_gate_s_proto_rawDescGZIP(), []int{9}
}

func (x *GateSendToMultiAddrRes) GetResult() map[string]bool {
	if x != nil {
		return x.Result
	}
	return nil
}

type GateSendToAllReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty" bson:"payload"`
}

func (x *GateSendToAllReq) Reset() {
	*x = GateSendToAllReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gate_s_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateSendToAllReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateSendToAllReq) ProtoMessage() {}

func (x *GateSendToAllReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_gate_s_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateSendToAllReq.ProtoReflect.Descriptor instead.
func (*GateSendToAllReq) Descriptor() ([]byte, []int) {
	return file_service_gate_s_proto_rawDescGZIP(), []int{10}
}

func (x *GateSendToAllReq) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type GateSendToAllRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GateSendToAllRes) Reset() {
	*x = GateSendToAllRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gate_s_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateSendToAllRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateSendToAllRes) ProtoMessage() {}

func (x *GateSendToAllRes) ProtoReflect() protoreflect.Message {
	mi := &file_service_gate_s_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateSendToAllRes.ProtoReflect.Descriptor instead.
func (*GateSendToAllRes) Descriptor() ([]byte, []int) {
	return file_service_gate_s_proto_rawDescGZIP(), []int{11}
}

type GateCloseIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id"`
}

func (x *GateCloseIdReq) Reset() {
	*x = GateCloseIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gate_s_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateCloseIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateCloseIdReq) ProtoMessage() {}

func (x *GateCloseIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_gate_s_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateCloseIdReq.ProtoReflect.Descriptor instead.
func (*GateCloseIdReq) Descriptor() ([]byte, []int) {
	return file_service_gate_s_proto_rawDescGZIP(), []int{12}
}

func (x *GateCloseIdReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GateCloseIdRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GateCloseIdRes) Reset() {
	*x = GateCloseIdRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gate_s_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateCloseIdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateCloseIdRes) ProtoMessage() {}

func (x *GateCloseIdRes) ProtoReflect() protoreflect.Message {
	mi := &file_service_gate_s_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateCloseIdRes.ProtoReflect.Descriptor instead.
func (*GateCloseIdRes) Descriptor() ([]byte, []int) {
	return file_service_gate_s_proto_rawDescGZIP(), []int{13}
}

type GateCloseAddrReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty" bson:"addr"`
}

func (x *GateCloseAddrReq) Reset() {
	*x = GateCloseAddrReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gate_s_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateCloseAddrReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateCloseAddrReq) ProtoMessage() {}

func (x *GateCloseAddrReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_gate_s_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateCloseAddrReq.ProtoReflect.Descriptor instead.
func (*GateCloseAddrReq) Descriptor() ([]byte, []int) {
	return file_service_gate_s_proto_rawDescGZIP(), []int{14}
}

func (x *GateCloseAddrReq) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type GateCloseAddrRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GateCloseAddrRes) Reset() {
	*x = GateCloseAddrRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gate_s_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateCloseAddrRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateCloseAddrRes) ProtoMessage() {}

func (x *GateCloseAddrRes) ProtoReflect() protoreflect.Message {
	mi := &file_service_gate_s_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateCloseAddrRes.ProtoReflect.Descriptor instead.
func (*GateCloseAddrRes) Descriptor() ([]byte, []int) {
	return file_service_gate_s_proto_rawDescGZIP(), []int{15}
}

type GateUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id"`
	Head []byte `protobuf:"bytes,2,opt,name=head,proto3" json:"head,omitempty" bson:"head"`
}

func (x *GateUpdateReq) Reset() {
	*x = GateUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gate_s_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateUpdateReq) ProtoMessage() {}

func (x *GateUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_gate_s_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateUpdateReq.ProtoReflect.Descriptor instead.
func (*GateUpdateReq) Descriptor() ([]byte, []int) {
	return file_service_gate_s_proto_rawDescGZIP(), []int{16}
}

func (x *GateUpdateReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GateUpdateReq) GetHead() []byte {
	if x != nil {
		return x.Head
	}
	return nil
}

type GateUpdateRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GateUpdateRes) Reset() {
	*x = GateUpdateRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gate_s_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateUpdateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateUpdateRes) ProtoMessage() {}

func (x *GateUpdateRes) ProtoReflect() protoreflect.Message {
	mi := &file_service_gate_s_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateUpdateRes.ProtoReflect.Descriptor instead.
func (*GateUpdateRes) Descriptor() ([]byte, []int) {
	return file_service_gate_s_proto_rawDescGZIP(), []int{17}
}

type GateRemoveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id"`
	Head []string `protobuf:"bytes,2,rep,name=head,proto3" json:"head,omitempty" bson:"head"`
}

func (x *GateRemoveReq) Reset() {
	*x = GateRemoveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gate_s_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateRemoveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateRemoveReq) ProtoMessage() {}

func (x *GateRemoveReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_gate_s_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateRemoveReq.ProtoReflect.Descriptor instead.
func (*GateRemoveReq) Descriptor() ([]byte, []int) {
	return file_service_gate_s_proto_rawDescGZIP(), []int{18}
}

func (x *GateRemoveReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GateRemoveReq) GetHead() []string {
	if x != nil {
		return x.Head
	}
	return nil
}

type GateRemoveRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GateRemoveRes) Reset() {
	*x = GateRemoveRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gate_s_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateRemoveRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateRemoveRes) ProtoMessage() {}

func (x *GateRemoveRes) ProtoReflect() protoreflect.Message {
	mi := &file_service_gate_s_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateRemoveRes.ProtoReflect.Descriptor instead.
func (*GateRemoveRes) Descriptor() ([]byte, []int) {
	return file_service_gate_s_proto_rawDescGZIP(), []int{19}
}

type GateGetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id"`
	Close bool   `protobuf:"varint,2,opt,name=close,proto3" json:"close,omitempty" bson:"close"` //关闭重复链接
}

func (x *GateGetReq) Reset() {
	*x = GateGetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gate_s_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateGetReq) ProtoMessage() {}

func (x *GateGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_gate_s_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateGetReq.ProtoReflect.Descriptor instead.
func (*GateGetReq) Descriptor() ([]byte, []int) {
	return file_service_gate_s_proto_rawDescGZIP(), []int{20}
}

func (x *GateGetReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GateGetReq) GetClose() bool {
	if x != nil {
		return x.Close
	}
	return false
}

type GateGetRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Head []byte `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty" bson:"head"`
}

func (x *GateGetRes) Reset() {
	*x = GateGetRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gate_s_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateGetRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateGetRes) ProtoMessage() {}

func (x *GateGetRes) ProtoReflect() protoreflect.Message {
	mi := &file_service_gate_s_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateGetRes.ProtoReflect.Descriptor instead.
func (*GateGetRes) Descriptor() ([]byte, []int) {
	return file_service_gate_s_proto_rawDescGZIP(), []int{21}
}

func (x *GateGetRes) GetHead() []byte {
	if x != nil {
		return x.Head
	}
	return nil
}

type GateUpdateRolesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roles map[uint32]int64 `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3" bson:"roles"` //SvcMethod:role mask
}

func (x *GateUpdateRolesReq) Reset() {
	*x = GateUpdateRolesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gate_s_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateUpdateRolesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateUpdateRolesReq) ProtoMessage() {}

func (x *GateUpdateRolesReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_gate_s_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateUpdateRolesReq.ProtoReflect.Descriptor instead.
func (*GateUpdateRolesReq) Descriptor() ([]byte, []int) {
	return file_service_gate_s_proto_rawDescGZIP(), []int{22}
}

func (x *GateUpdateRolesReq) GetRoles() map[uint32]int64 {
	if x != nil {
		return x.Roles
	}
	return nil
}

type GateUpdateRolesRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GateUpdateRolesRes) Reset() {
	*x = GateUpdateRolesRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gate_s_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateUpdateRolesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateUpdateRolesRes) ProtoMessage() {}

func (x *GateUpdateRolesRes) ProtoReflect() protoreflect.Message {
	mi := &file_service_gate_s_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateUpdateRolesRes.ProtoReflect.Descriptor instead.
func (*GateUpdateRolesRes) Descriptor() ([]byte, []int) {
	return file_service_gate_s_proto_rawDescGZIP(), []int{23}
}

var File_service_gate_s_proto protoreflect.FileDescriptor

var file_service_gate_s_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x5f, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x25, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x31, 0x35, 0x6d, 0x67, 0x61, 0x2f, 0x6b, 0x69, 0x77,
	0x69, 0x5f, 0x74, 0x6f, 0x6f, 0x6c, 0x2f, 0x6b, 0x69, 0x77, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x2b, 0x0a, 0x0e, 0x47, 0x61, 0x74, 0x65, 0x42, 0x61, 0x6e, 0x41, 0x64, 0x64, 0x72,
	0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x3a, 0x05, 0xe0, 0xe3, 0x49, 0xf4, 0x03, 0x22, 0x17,
	0x0a, 0x0e, 0x47, 0x61, 0x74, 0x65, 0x42, 0x61, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x73,
	0x3a, 0x05, 0xe0, 0xe3, 0x49, 0xf5, 0x03, 0x22, 0x42, 0x0a, 0x0f, 0x47, 0x61, 0x74, 0x65, 0x53,
	0x65, 0x6e, 0x64, 0x54, 0x6f, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x3a, 0x05, 0xe0, 0xe3, 0x49, 0xf6, 0x03, 0x22, 0x18, 0x0a, 0x0f, 0x47,
	0x61, 0x74, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x49, 0x64, 0x52, 0x65, 0x73, 0x3a, 0x05,
	0xe0, 0xe3, 0x49, 0xf7, 0x03, 0x22, 0x48, 0x0a, 0x11, 0x47, 0x61, 0x74, 0x65, 0x53, 0x65, 0x6e,
	0x64, 0x54, 0x6f, 0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64,
	0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x3a, 0x05, 0xe0, 0xe3, 0x49, 0xf8, 0x03, 0x22,
	0x1a, 0x0a, 0x11, 0x47, 0x61, 0x74, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x41, 0x64, 0x64,
	0x72, 0x52, 0x65, 0x73, 0x3a, 0x05, 0xe0, 0xe3, 0x49, 0xf9, 0x03, 0x22, 0x37, 0x0a, 0x14, 0x47,
	0x61, 0x74, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x49, 0x64,
	0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x3a, 0x05, 0xe0,
	0xe3, 0x49, 0xfa, 0x03, 0x22, 0x96, 0x01, 0x0a, 0x14, 0x47, 0x61, 0x74, 0x65, 0x53, 0x65, 0x6e,
	0x64, 0x54, 0x6f, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x49, 0x64, 0x52, 0x65, 0x73, 0x12, 0x3c, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e,
	0x70, 0x62, 0x2e, 0x47, 0x61, 0x74, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x4d, 0x75, 0x6c,
	0x74, 0x69, 0x49, 0x64, 0x52, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x1a, 0x39, 0x0a, 0x0b, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x3a, 0x05, 0xe0, 0xe3, 0x49, 0xfb, 0x03, 0x22, 0x39, 0x0a,
	0x16, 0x47, 0x61, 0x74, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x4d, 0x75, 0x6c, 0x74, 0x69,
	0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x3a, 0x05, 0xe0, 0xe3, 0x49, 0xfc, 0x03, 0x22, 0x9a, 0x01, 0x0a, 0x16, 0x47, 0x61, 0x74,
	0x65, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x41, 0x64, 0x64, 0x72,
	0x52, 0x65, 0x73, 0x12, 0x3e, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x61, 0x74, 0x65, 0x53, 0x65, 0x6e,
	0x64, 0x54, 0x6f, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x73, 0x2e,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x1a, 0x39, 0x0a, 0x0b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x3a, 0x05,
	0xe0, 0xe3, 0x49, 0xfd, 0x03, 0x22, 0x33, 0x0a, 0x10, 0x47, 0x61, 0x74, 0x65, 0x53, 0x65, 0x6e,
	0x64, 0x54, 0x6f, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x3a, 0x05, 0xe0, 0xe3, 0x49, 0xfe, 0x03, 0x22, 0x19, 0x0a, 0x10, 0x47, 0x61,
	0x74, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x3a, 0x05,
	0xe0, 0xe3, 0x49, 0xff, 0x03, 0x22, 0x27, 0x0a, 0x0e, 0x47, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x6f,
	0x73, 0x65, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x3a, 0x05, 0xe0, 0xe3, 0x49, 0x80, 0x04, 0x22, 0x17,
	0x0a, 0x0e, 0x47, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x49, 0x64, 0x52, 0x65, 0x73,
	0x3a, 0x05, 0xe0, 0xe3, 0x49, 0x81, 0x04, 0x22, 0x2d, 0x0a, 0x10, 0x47, 0x61, 0x74, 0x65, 0x43,
	0x6c, 0x6f, 0x73, 0x65, 0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x61,
	0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x3a,
	0x05, 0xe0, 0xe3, 0x49, 0x82, 0x04, 0x22, 0x19, 0x0a, 0x10, 0x47, 0x61, 0x74, 0x65, 0x43, 0x6c,
	0x6f, 0x73, 0x65, 0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x73, 0x3a, 0x05, 0xe0, 0xe3, 0x49, 0x83,
	0x04, 0x22, 0x3a, 0x0a, 0x0d, 0x47, 0x61, 0x74, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x3a, 0x05, 0xe0, 0xe3, 0x49, 0x84, 0x04, 0x22, 0x16, 0x0a,
	0x0d, 0x47, 0x61, 0x74, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x3a, 0x05,
	0xe0, 0xe3, 0x49, 0x85, 0x04, 0x22, 0x3a, 0x0a, 0x0d, 0x47, 0x61, 0x74, 0x65, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x64, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x3a, 0x05, 0xe0, 0xe3, 0x49, 0x88,
	0x04, 0x22, 0x16, 0x0a, 0x0d, 0x47, 0x61, 0x74, 0x65, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52,
	0x65, 0x73, 0x3a, 0x05, 0xe0, 0xe3, 0x49, 0x89, 0x04, 0x22, 0x39, 0x0a, 0x0a, 0x47, 0x61, 0x74,
	0x65, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x3a, 0x05, 0xe0,
	0xe3, 0x49, 0x8c, 0x04, 0x22, 0x27, 0x0a, 0x0a, 0x47, 0x61, 0x74, 0x65, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x3a, 0x05, 0xe0, 0xe3, 0x49, 0x8d, 0x04, 0x22, 0x8e, 0x01,
	0x0a, 0x12, 0x47, 0x61, 0x74, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x12, 0x37, 0x0a, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x61, 0x74, 0x65, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x2e, 0x52, 0x6f, 0x6c, 0x65,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x1a, 0x38, 0x0a,
	0x0a, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x3a, 0x05, 0xe0, 0xe3, 0x49, 0x8e, 0x04, 0x22, 0x1b,
	0x0a, 0x12, 0x47, 0x61, 0x74, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x3a, 0x05, 0xe0, 0xe3, 0x49, 0x8f, 0x04, 0x42, 0x22, 0xca, 0xdd, 0x49,
	0x14, 0x08, 0x01, 0x12, 0x04, 0x67, 0x61, 0x74, 0x65, 0x1a, 0x0a, 0x08, 0x04, 0x10, 0x01, 0x1a,
	0x04, 0x61, 0x64, 0x64, 0x72, 0x5a, 0x03, 0x2f, 0x70, 0x62, 0xaa, 0x02, 0x02, 0x50, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_gate_s_proto_rawDescOnce sync.Once
	file_service_gate_s_proto_rawDescData = file_service_gate_s_proto_rawDesc
)

func file_service_gate_s_proto_rawDescGZIP() []byte {
	file_service_gate_s_proto_rawDescOnce.Do(func() {
		file_service_gate_s_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_gate_s_proto_rawDescData)
	})
	return file_service_gate_s_proto_rawDescData
}

var file_service_gate_s_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_service_gate_s_proto_goTypes = []interface{}{
	(*GateBanAddrReq)(nil),         // 0: pb.GateBanAddrReq
	(*GateBanAddrRes)(nil),         // 1: pb.GateBanAddrRes
	(*GateSendToIdReq)(nil),        // 2: pb.GateSendToIdReq
	(*GateSendToIdRes)(nil),        // 3: pb.GateSendToIdRes
	(*GateSendToAddrReq)(nil),      // 4: pb.GateSendToAddrReq
	(*GateSendToAddrRes)(nil),      // 5: pb.GateSendToAddrRes
	(*GateSendToMultiIdReq)(nil),   // 6: pb.GateSendToMultiIdReq
	(*GateSendToMultiIdRes)(nil),   // 7: pb.GateSendToMultiIdRes
	(*GateSendToMultiAddrReq)(nil), // 8: pb.GateSendToMultiAddrReq
	(*GateSendToMultiAddrRes)(nil), // 9: pb.GateSendToMultiAddrRes
	(*GateSendToAllReq)(nil),       // 10: pb.GateSendToAllReq
	(*GateSendToAllRes)(nil),       // 11: pb.GateSendToAllRes
	(*GateCloseIdReq)(nil),         // 12: pb.GateCloseIdReq
	(*GateCloseIdRes)(nil),         // 13: pb.GateCloseIdRes
	(*GateCloseAddrReq)(nil),       // 14: pb.GateCloseAddrReq
	(*GateCloseAddrRes)(nil),       // 15: pb.GateCloseAddrRes
	(*GateUpdateReq)(nil),          // 16: pb.GateUpdateReq
	(*GateUpdateRes)(nil),          // 17: pb.GateUpdateRes
	(*GateRemoveReq)(nil),          // 18: pb.GateRemoveReq
	(*GateRemoveRes)(nil),          // 19: pb.GateRemoveRes
	(*GateGetReq)(nil),             // 20: pb.GateGetReq
	(*GateGetRes)(nil),             // 21: pb.GateGetRes
	(*GateUpdateRolesReq)(nil),     // 22: pb.GateUpdateRolesReq
	(*GateUpdateRolesRes)(nil),     // 23: pb.GateUpdateRolesRes
	nil,                            // 24: pb.GateSendToMultiIdRes.ResultEntry
	nil,                            // 25: pb.GateSendToMultiAddrRes.ResultEntry
	nil,                            // 26: pb.GateUpdateRolesReq.RolesEntry
}
var file_service_gate_s_proto_depIdxs = []int32{
	24, // 0: pb.GateSendToMultiIdRes.result:type_name -> pb.GateSendToMultiIdRes.ResultEntry
	25, // 1: pb.GateSendToMultiAddrRes.result:type_name -> pb.GateSendToMultiAddrRes.ResultEntry
	26, // 2: pb.GateUpdateRolesReq.roles:type_name -> pb.GateUpdateRolesReq.RolesEntry
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_service_gate_s_proto_init() }
func file_service_gate_s_proto_init() {
	if File_service_gate_s_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_gate_s_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateBanAddrReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gate_s_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateBanAddrRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gate_s_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateSendToIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gate_s_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateSendToIdRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gate_s_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateSendToAddrReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gate_s_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateSendToAddrRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gate_s_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateSendToMultiIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gate_s_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateSendToMultiIdRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gate_s_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateSendToMultiAddrReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gate_s_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateSendToMultiAddrRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gate_s_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateSendToAllReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gate_s_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateSendToAllRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gate_s_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateCloseIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gate_s_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateCloseIdRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gate_s_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateCloseAddrReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gate_s_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateCloseAddrRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gate_s_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gate_s_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateUpdateRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gate_s_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateRemoveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gate_s_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateRemoveRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gate_s_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateGetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gate_s_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateGetRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gate_s_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateUpdateRolesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gate_s_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateUpdateRolesRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_gate_s_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_service_gate_s_proto_goTypes,
		DependencyIndexes: file_service_gate_s_proto_depIdxs,
		MessageInfos:      file_service_gate_s_proto_msgTypes,
	}.Build()
	File_service_gate_s_proto = out.File
	file_service_gate_s_proto_rawDesc = nil
	file_service_gate_s_proto_goTypes = nil
	file_service_gate_s_proto_depIdxs = nil
}
