// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.20.1
// source: client/group_c.proto

package pb

import (
	_ "github.com/15mga/kiwi_tool"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupNewReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GroupNewReq) Reset() {
	*x = GroupNewReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_group_c_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupNewReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupNewReq) ProtoMessage() {}

func (x *GroupNewReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_group_c_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupNewReq.ProtoReflect.Descriptor instead.
func (*GroupNewReq) Descriptor() ([]byte, []int) {
	return file_client_group_c_proto_rawDescGZIP(), []int{0}
}

var File_client_group_c_proto protoreflect.FileDescriptor

var file_client_group_c_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x63,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x25, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x31, 0x35, 0x6d, 0x67, 0x61, 0x2f, 0x6b, 0x69, 0x77,
	0x69, 0x5f, 0x74, 0x6f, 0x6f, 0x6c, 0x2f, 0x6b, 0x69, 0x77, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x1d, 0x0a, 0x0b, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x65, 0x77, 0x52, 0x65, 0x71,
	0x3a, 0x0e, 0xe0, 0xe3, 0x49, 0x00, 0xea, 0xe3, 0x49, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x42, 0x15, 0xca, 0xdd, 0x49, 0x07, 0x12, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5a, 0x03, 0x2f,
	0x70, 0x62, 0xaa, 0x02, 0x02, 0x50, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_client_group_c_proto_rawDescOnce sync.Once
	file_client_group_c_proto_rawDescData = file_client_group_c_proto_rawDesc
)

func file_client_group_c_proto_rawDescGZIP() []byte {
	file_client_group_c_proto_rawDescOnce.Do(func() {
		file_client_group_c_proto_rawDescData = protoimpl.X.CompressGZIP(file_client_group_c_proto_rawDescData)
	})
	return file_client_group_c_proto_rawDescData
}

var file_client_group_c_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_client_group_c_proto_goTypes = []interface{}{
	(*GroupNewReq)(nil), // 0: pb.GroupNewReq
}
var file_client_group_c_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_client_group_c_proto_init() }
func file_client_group_c_proto_init() {
	if File_client_group_c_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_client_group_c_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupNewReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_client_group_c_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_group_c_proto_goTypes,
		DependencyIndexes: file_client_group_c_proto_depIdxs,
		MessageInfos:      file_client_group_c_proto_msgTypes,
	}.Build()
	File_client_group_c_proto = out.File
	file_client_group_c_proto_rawDesc = nil
	file_client_group_c_proto_goTypes = nil
	file_client_group_c_proto_depIdxs = nil
}
