// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: client/user_c.proto

package pb

import (
	_ "github.com/15mga/kiwi_tool"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 注册
type UserSignUpReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mobile   string `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile" bson:"mobile"`       //手机号
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password" bson:"password"` //密码
	Code     string `protobuf:"bytes,3,opt,name=code,proto3" json:"code" bson:"code"`             //短信验证码
	Nick     string `protobuf:"bytes,4,opt,name=nick,proto3" json:"nick" bson:"nick"`             //昵称
	Avatar   string `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar" bson:"avatar"`       //头像
}

func (x *UserSignUpReq) Reset() {
	*x = UserSignUpReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_user_c_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserSignUpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSignUpReq) ProtoMessage() {}

func (x *UserSignUpReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_user_c_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSignUpReq.ProtoReflect.Descriptor instead.
func (*UserSignUpReq) Descriptor() ([]byte, []int) {
	return file_client_user_c_proto_rawDescGZIP(), []int{0}
}

func (x *UserSignUpReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *UserSignUpReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserSignUpReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UserSignUpReq) GetNick() string {
	if x != nil {
		return x.Nick
	}
	return ""
}

func (x *UserSignUpReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

// 注册
type UserSignUpRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserSignUpRes) Reset() {
	*x = UserSignUpRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_user_c_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserSignUpRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSignUpRes) ProtoMessage() {}

func (x *UserSignUpRes) ProtoReflect() protoreflect.Message {
	mi := &file_client_user_c_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSignUpRes.ProtoReflect.Descriptor instead.
func (*UserSignUpRes) Descriptor() ([]byte, []int) {
	return file_client_user_c_proto_rawDescGZIP(), []int{1}
}

// 登录
type UserSignInReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mobile   string `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile" bson:"mobile"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password" bson:"password"`
	Os       string `protobuf:"bytes,3,opt,name=os,proto3" json:"os" bson:"os"`
}

func (x *UserSignInReq) Reset() {
	*x = UserSignInReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_user_c_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserSignInReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSignInReq) ProtoMessage() {}

func (x *UserSignInReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_user_c_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSignInReq.ProtoReflect.Descriptor instead.
func (*UserSignInReq) Descriptor() ([]byte, []int) {
	return file_client_user_c_proto_rawDescGZIP(), []int{2}
}

func (x *UserSignInReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *UserSignInReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserSignInReq) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

// 登录
type UserSignInRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token" bson:"token"`
}

func (x *UserSignInRes) Reset() {
	*x = UserSignInRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_user_c_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserSignInRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSignInRes) ProtoMessage() {}

func (x *UserSignInRes) ProtoReflect() protoreflect.Message {
	mi := &file_client_user_c_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSignInRes.ProtoReflect.Descriptor instead.
func (*UserSignInRes) Descriptor() ([]byte, []int) {
	return file_client_user_c_proto_rawDescGZIP(), []int{3}
}

func (x *UserSignInRes) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 重置密码
type UserResetPasswordReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mobile   string `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile" bson:"mobile"`       //手机号
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password" bson:"password"` //密码
	Code     string `protobuf:"bytes,3,opt,name=code,proto3" json:"code" bson:"code"`             //短信验证码
}

func (x *UserResetPasswordReq) Reset() {
	*x = UserResetPasswordReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_user_c_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserResetPasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResetPasswordReq) ProtoMessage() {}

func (x *UserResetPasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_user_c_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResetPasswordReq.ProtoReflect.Descriptor instead.
func (*UserResetPasswordReq) Descriptor() ([]byte, []int) {
	return file_client_user_c_proto_rawDescGZIP(), []int{4}
}

func (x *UserResetPasswordReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *UserResetPasswordReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserResetPasswordReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// 重置密码
type UserResetPasswordRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token" bson:"token"`
}

func (x *UserResetPasswordRes) Reset() {
	*x = UserResetPasswordRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_user_c_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserResetPasswordRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResetPasswordRes) ProtoMessage() {}

func (x *UserResetPasswordRes) ProtoReflect() protoreflect.Message {
	mi := &file_client_user_c_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResetPasswordRes.ProtoReflect.Descriptor instead.
func (*UserResetPasswordRes) Descriptor() ([]byte, []int) {
	return file_client_user_c_proto_rawDescGZIP(), []int{5}
}

func (x *UserResetPasswordRes) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 短信验证码
type UserSmsCodeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mobile string `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile" bson:"mobile"` //手机号
}

func (x *UserSmsCodeReq) Reset() {
	*x = UserSmsCodeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_user_c_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserSmsCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSmsCodeReq) ProtoMessage() {}

func (x *UserSmsCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_user_c_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSmsCodeReq.ProtoReflect.Descriptor instead.
func (*UserSmsCodeReq) Descriptor() ([]byte, []int) {
	return file_client_user_c_proto_rawDescGZIP(), []int{6}
}

func (x *UserSmsCodeReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

// 短信验证码
type UserSmsCodeRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserSmsCodeRes) Reset() {
	*x = UserSmsCodeRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_user_c_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserSmsCodeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSmsCodeRes) ProtoMessage() {}

func (x *UserSmsCodeRes) ProtoReflect() protoreflect.Message {
	mi := &file_client_user_c_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSmsCodeRes.ProtoReflect.Descriptor instead.
func (*UserSmsCodeRes) Descriptor() ([]byte, []int) {
	return file_client_user_c_proto_rawDescGZIP(), []int{7}
}

// 登出请求
type UserSignOutReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserSignOutReq) Reset() {
	*x = UserSignOutReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_user_c_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserSignOutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSignOutReq) ProtoMessage() {}

func (x *UserSignOutReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_user_c_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSignOutReq.ProtoReflect.Descriptor instead.
func (*UserSignOutReq) Descriptor() ([]byte, []int) {
	return file_client_user_c_proto_rawDescGZIP(), []int{8}
}

// 登出响应
type UserSignOutRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserSignOutRes) Reset() {
	*x = UserSignOutRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_user_c_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserSignOutRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSignOutRes) ProtoMessage() {}

func (x *UserSignOutRes) ProtoReflect() protoreflect.Message {
	mi := &file_client_user_c_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSignOutRes.ProtoReflect.Descriptor instead.
func (*UserSignOutRes) Descriptor() ([]byte, []int) {
	return file_client_user_c_proto_rawDescGZIP(), []int{9}
}

var File_client_user_c_proto protoreflect.FileDescriptor

var file_client_user_c_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x63, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x31, 0x35, 0x6d, 0x67, 0x61, 0x2f, 0x6b, 0x69, 0x77, 0x69,
	0x5f, 0x74, 0x6f, 0x6f, 0x6c, 0x2f, 0x6b, 0x69, 0x77, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x92, 0x01, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x52,
	0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x69,
	0x63, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x69, 0x63, 0x6b, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x3a, 0x0d, 0xe0, 0xe3, 0x49, 0x00, 0xea, 0xe3, 0x49, 0x05,
	0x67, 0x75, 0x65, 0x73, 0x74, 0x22, 0x15, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x53, 0x69, 0x67,
	0x6e, 0x55, 0x70, 0x52, 0x65, 0x73, 0x3a, 0x04, 0xe0, 0xe3, 0x49, 0x01, 0x22, 0x62, 0x0a, 0x0d,
	0x55, 0x73, 0x65, 0x72, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a,
	0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d,
	0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f,
	0x73, 0x3a, 0x0d, 0xe0, 0xe3, 0x49, 0x02, 0xea, 0xe3, 0x49, 0x05, 0x67, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x2b, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x52, 0x65,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x3a, 0x04, 0xe0, 0xe3, 0x49, 0x03, 0x22, 0x6d, 0x0a,
	0x14, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x3a, 0x0d, 0xe0,
	0xe3, 0x49, 0x04, 0xea, 0xe3, 0x49, 0x05, 0x67, 0x75, 0x65, 0x73, 0x74, 0x22, 0x32, 0x0a, 0x14,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x52, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x3a, 0x04, 0xe0, 0xe3, 0x49, 0x05,
	0x22, 0x37, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x6d, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x3a, 0x0d, 0xe0, 0xe3, 0x49, 0x06,
	0xea, 0xe3, 0x49, 0x05, 0x67, 0x75, 0x65, 0x73, 0x74, 0x22, 0x16, 0x0a, 0x0e, 0x55, 0x73, 0x65,
	0x72, 0x53, 0x6d, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x3a, 0x04, 0xe0, 0xe3, 0x49,
	0x07, 0x22, 0x20, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x69, 0x67, 0x6e, 0x4f, 0x75, 0x74,
	0x52, 0x65, 0x71, 0x3a, 0x0e, 0xe0, 0xe3, 0x49, 0x08, 0xea, 0xe3, 0x49, 0x06, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x22, 0x16, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x69, 0x67, 0x6e, 0x4f,
	0x75, 0x74, 0x52, 0x65, 0x73, 0x3a, 0x04, 0xe0, 0xe3, 0x49, 0x09, 0x42, 0x14, 0xca, 0xdd, 0x49,
	0x06, 0x12, 0x04, 0x75, 0x73, 0x65, 0x72, 0x5a, 0x03, 0x2f, 0x70, 0x62, 0xaa, 0x02, 0x02, 0x50,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_client_user_c_proto_rawDescOnce sync.Once
	file_client_user_c_proto_rawDescData = file_client_user_c_proto_rawDesc
)

func file_client_user_c_proto_rawDescGZIP() []byte {
	file_client_user_c_proto_rawDescOnce.Do(func() {
		file_client_user_c_proto_rawDescData = protoimpl.X.CompressGZIP(file_client_user_c_proto_rawDescData)
	})
	return file_client_user_c_proto_rawDescData
}

var file_client_user_c_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_client_user_c_proto_goTypes = []interface{}{
	(*UserSignUpReq)(nil),        // 0: pb.UserSignUpReq
	(*UserSignUpRes)(nil),        // 1: pb.UserSignUpRes
	(*UserSignInReq)(nil),        // 2: pb.UserSignInReq
	(*UserSignInRes)(nil),        // 3: pb.UserSignInRes
	(*UserResetPasswordReq)(nil), // 4: pb.UserResetPasswordReq
	(*UserResetPasswordRes)(nil), // 5: pb.UserResetPasswordRes
	(*UserSmsCodeReq)(nil),       // 6: pb.UserSmsCodeReq
	(*UserSmsCodeRes)(nil),       // 7: pb.UserSmsCodeRes
	(*UserSignOutReq)(nil),       // 8: pb.UserSignOutReq
	(*UserSignOutRes)(nil),       // 9: pb.UserSignOutRes
}
var file_client_user_c_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_client_user_c_proto_init() }
func file_client_user_c_proto_init() {
	if File_client_user_c_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_client_user_c_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserSignUpReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_user_c_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserSignUpRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_user_c_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserSignInReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_user_c_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserSignInRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_user_c_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserResetPasswordReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_user_c_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserResetPasswordRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_user_c_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserSmsCodeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_user_c_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserSmsCodeRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_user_c_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserSignOutReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_user_c_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserSignOutRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_client_user_c_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_user_c_proto_goTypes,
		DependencyIndexes: file_client_user_c_proto_depIdxs,
		MessageInfos:      file_client_user_c_proto_msgTypes,
	}.Build()
	File_client_user_c_proto = out.File
	file_client_user_c_proto_rawDesc = nil
	file_client_user_c_proto_goTypes = nil
	file_client_user_c_proto_depIdxs = nil
}
