// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.20.1
// source: service/user_s.proto

package pb

import (
	_ "github.com/15mga/kiwi_tool"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserDisconnectReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty" bson:"user_id"`
}

func (x *UserDisconnectReq) Reset() {
	*x = UserDisconnectReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_user_s_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDisconnectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDisconnectReq) ProtoMessage() {}

func (x *UserDisconnectReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_s_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDisconnectReq.ProtoReflect.Descriptor instead.
func (*UserDisconnectReq) Descriptor() ([]byte, []int) {
	return file_service_user_s_proto_rawDescGZIP(), []int{0}
}

func (x *UserDisconnectReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserDisconnectRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserDisconnectRes) Reset() {
	*x = UserDisconnectRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_user_s_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDisconnectRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDisconnectRes) ProtoMessage() {}

func (x *UserDisconnectRes) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_s_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDisconnectRes.ProtoReflect.Descriptor instead.
func (*UserDisconnectRes) Descriptor() ([]byte, []int) {
	return file_service_user_s_proto_rawDescGZIP(), []int{1}
}

type UserDisconnectedNtc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty" bson:"uid"`
}

func (x *UserDisconnectedNtc) Reset() {
	*x = UserDisconnectedNtc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_user_s_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDisconnectedNtc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDisconnectedNtc) ProtoMessage() {}

func (x *UserDisconnectedNtc) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_s_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDisconnectedNtc.ProtoReflect.Descriptor instead.
func (*UserDisconnectedNtc) Descriptor() ([]byte, []int) {
	return file_service_user_s_proto_rawDescGZIP(), []int{2}
}

func (x *UserDisconnectedNtc) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type UserConnectedNtc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id"`
}

func (x *UserConnectedNtc) Reset() {
	*x = UserConnectedNtc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_user_s_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserConnectedNtc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserConnectedNtc) ProtoMessage() {}

func (x *UserConnectedNtc) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_s_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserConnectedNtc.ProtoReflect.Descriptor instead.
func (*UserConnectedNtc) Descriptor() ([]byte, []int) {
	return file_service_user_s_proto_rawDescGZIP(), []int{3}
}

func (x *UserConnectedNtc) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 更新用户head cache
type UserUpdateHeadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id"` //用户id
	Head []byte `protobuf:"bytes,2,opt,name=head,proto3" json:"head,omitempty" bson:"head"`
}

func (x *UserUpdateHeadReq) Reset() {
	*x = UserUpdateHeadReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_user_s_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserUpdateHeadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdateHeadReq) ProtoMessage() {}

func (x *UserUpdateHeadReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_s_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdateHeadReq.ProtoReflect.Descriptor instead.
func (*UserUpdateHeadReq) Descriptor() ([]byte, []int) {
	return file_service_user_s_proto_rawDescGZIP(), []int{4}
}

func (x *UserUpdateHeadReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserUpdateHeadReq) GetHead() []byte {
	if x != nil {
		return x.Head
	}
	return nil
}

type UserUpdateHeadRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserUpdateHeadRes) Reset() {
	*x = UserUpdateHeadRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_user_s_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserUpdateHeadRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdateHeadRes) ProtoMessage() {}

func (x *UserUpdateHeadRes) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_s_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdateHeadRes.ProtoReflect.Descriptor instead.
func (*UserUpdateHeadRes) Descriptor() ([]byte, []int) {
	return file_service_user_s_proto_rawDescGZIP(), []int{5}
}

var File_service_user_s_proto protoreflect.FileDescriptor

var file_service_user_s_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x25, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x31, 0x35, 0x6d, 0x67, 0x61, 0x2f, 0x6b, 0x69, 0x77,
	0x69, 0x5f, 0x74, 0x6f, 0x6f, 0x6c, 0x2f, 0x6b, 0x69, 0x77, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x32, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x3a, 0x05,
	0xe0, 0xe3, 0x49, 0xf4, 0x03, 0x22, 0x1a, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x44, 0x69, 0x73,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x3a, 0x05, 0xe0, 0xe3, 0x49, 0xf5,
	0x03, 0x22, 0x2e, 0x0a, 0x13, 0x55, 0x73, 0x65, 0x72, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x65, 0x64, 0x4e, 0x74, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x3a, 0x05, 0xe0, 0xe3, 0x49, 0xf6,
	0x03, 0x22, 0x29, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x65, 0x64, 0x4e, 0x74, 0x63, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x3a, 0x05, 0xe0, 0xe3, 0x49, 0xf7, 0x03, 0x22, 0x3e, 0x0a, 0x11,
	0x55, 0x73, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x65, 0x61, 0x64, 0x52, 0x65,
	0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x68, 0x65, 0x61, 0x64, 0x3a, 0x05, 0xe0, 0xe3, 0x49, 0xf8, 0x03, 0x22, 0x1a, 0x0a, 0x11,
	0x55, 0x73, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x65, 0x61, 0x64, 0x52, 0x65,
	0x73, 0x3a, 0x05, 0xe0, 0xe3, 0x49, 0xf9, 0x03, 0x42, 0x26, 0xca, 0xdd, 0x49, 0x18, 0x08, 0x02,
	0x12, 0x04, 0x75, 0x73, 0x65, 0x72, 0x1a, 0x08, 0x08, 0x01, 0x10, 0x01, 0x1a, 0x02, 0x69, 0x64,
	0x3a, 0x04, 0x67, 0x61, 0x74, 0x65, 0x5a, 0x03, 0x2f, 0x70, 0x62, 0xaa, 0x02, 0x02, 0x50, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_user_s_proto_rawDescOnce sync.Once
	file_service_user_s_proto_rawDescData = file_service_user_s_proto_rawDesc
)

func file_service_user_s_proto_rawDescGZIP() []byte {
	file_service_user_s_proto_rawDescOnce.Do(func() {
		file_service_user_s_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_user_s_proto_rawDescData)
	})
	return file_service_user_s_proto_rawDescData
}

var file_service_user_s_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_service_user_s_proto_goTypes = []interface{}{
	(*UserDisconnectReq)(nil),   // 0: pb.UserDisconnectReq
	(*UserDisconnectRes)(nil),   // 1: pb.UserDisconnectRes
	(*UserDisconnectedNtc)(nil), // 2: pb.UserDisconnectedNtc
	(*UserConnectedNtc)(nil),    // 3: pb.UserConnectedNtc
	(*UserUpdateHeadReq)(nil),   // 4: pb.UserUpdateHeadReq
	(*UserUpdateHeadRes)(nil),   // 5: pb.UserUpdateHeadRes
}
var file_service_user_s_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_user_s_proto_init() }
func file_service_user_s_proto_init() {
	if File_service_user_s_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_user_s_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDisconnectReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_user_s_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDisconnectRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_user_s_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDisconnectedNtc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_user_s_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserConnectedNtc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_user_s_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserUpdateHeadReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_user_s_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserUpdateHeadRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_user_s_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_service_user_s_proto_goTypes,
		DependencyIndexes: file_service_user_s_proto_depIdxs,
		MessageInfos:      file_service_user_s_proto_msgTypes,
	}.Build()
	File_service_user_s_proto = out.File
	file_service_user_s_proto_rawDesc = nil
	file_service_user_s_proto_goTypes = nil
	file_service_user_s_proto_depIdxs = nil
}
