// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package common

// gate
const (
	//id不存在
	EcGateNotExistId = 11001
	//地址不存在
	EcGateNotExistAddr = 11002
)

// user
const (
	//手机号错误
	EcMobileWrong = 0
	//密码错误
	EcPasswordWrong = 1
	//手机号已存在
	EcMobileExist = 2
	//手机号已存在
	EcNickExist = 3
	//验证码错误
	EcSmsWrong = 4
	//账号或密码错误
	EcWrongMobileOrPassword = 5
)
