// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package common

// gate 1
const (
	//id不存在
	EcGateNotExistId = 1000
	//地址不存在
	EcGateNotExistAddr = 1001
)

// user 2
const (
	//手机号错误
	EcMobileWrong = 2000
	//密码错误
	EcPasswordWrong = 2001
	//手机号已存在
	EcMobileExist = 2002
	//手机号已存在
	EcNickExist = 2003
	//验证码错误
	EcSmsWrong = 2004
	//账号或密码错误
	EcWrongMobileOrPassword = 2005
)

func init() {
	util.SetErrCodesToStrMap(map[util.TErrCode]string{
		1000: "gate not exist id",
		1001: "gate not exist addr",
		2000: "mobile wrong",
		2001: "password wrong",
		2002: "mobile exist",
		2003: "nick exist",
		2004: "sms wrong",
		2005: "wrong mobile or password",
	})
}
