// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package common

func RoleToStr(role int64) string {
	switch role {
	case RGuest:
		return "guest"
	case RPlayer:
		return "player"
	case ROps:
		return "ops"
	default:
		return ""
	}
}

func StrToRole(role string) int64 {
	switch role {
	case "guest":
		return RGuest
	case "player":
		return RPlayer
	case "ops":
		return ROps
	default:
		return 0
	}
}
