// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package common

import (
	"github.com/15mga/kiwi"
)

const (
	Gate  kiwi.TSvc = 1
	User  kiwi.TSvc = 2
	Group kiwi.TSvc = 3
)

const (
	SGate  = "gate"
	SUser  = "user"
	SGroup = "group"
)

var SvcToName = map[kiwi.TSvc]string{
	Gate:  SGate,
	User:  SUser,
	Group: SGroup,
}

var NameToSvc = map[string]kiwi.TSvc{
	SGate:  Gate,
	SUser:  User,
	SGroup: Group,
}
