// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package mock

import (
	"game/internal/mock/gate"
	"game/internal/mock/group"
	"game/internal/mock/user"
	"github.com/15mga/kiwi/mock"
)

func initClient(client *mock.Client) {
	gate.InitClient(client)
	user.InitClient(client)
	group.InitClient(client)
}
